- name: Deploy homelab services (Homepage)
  hosts: homelab
  become: true
  gather_facts: false

  pre_tasks:
    - name: Ensure python3-pip is installed
      ansible.builtin.yum:
        name: python3-pip
        state: present

  roles:
    - { role: homepage, tags: ["homepage"] }
    - { role: uptime_kuma, tags: ["uptime_kuma", "monitoring"] }
    - { role: apache, tags: ["apache", "web"] }
    - { role: portainer, tags: ["portainer"] }
    - { role: traefik, tags: ["traefik"] }
    - { role: database,  tags: ["database"] }
